#!/usr/bin/env python3
"""
Generate slide thumbnails from a PPTX file.

Converts PPTX → PDF via LibreOffice, then PDF → individual slide JPGs via pdftoppm,
and creates a grid overview image using Pillow.

Usage:
    python thumbnail.py input.pptx [output_dir]

Output:
    output_dir/slide-01.jpg, slide-02.jpg, ...
    output_dir/grid.jpg (overview grid of all slides)
"""

import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Import soffice_convert from the same directory
sys.path.insert(0, str(Path(__file__).parent))
from soffice_convert import convert_pptx_to_pdf


def pptx_to_slide_images(pptx_path: str, output_dir: str = None, dpi: int = 150) -> list:
    """
    Convert a PPTX file to individual slide JPG images.

    Args:
        pptx_path: Path to the .pptx file
        output_dir: Directory for output images. Defaults to same dir as input.
        dpi: Resolution for rendering (default 150)

    Returns:
        List of paths to generated slide JPG files.
    """
    pptx_path = Path(pptx_path).resolve()
    if not pptx_path.exists():
        raise FileNotFoundError(f"Input file not found: {pptx_path}")

    if output_dir:
        output_dir = Path(output_dir).resolve()
    else:
        output_dir = pptx_path.parent

    output_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: Convert PPTX to PDF
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_pdf = str(Path(tmpdir) / "presentation.pdf")
        convert_pptx_to_pdf(str(pptx_path), tmp_pdf)

        # Step 2: Convert PDF to JPGs via pdftoppm
        prefix = str(Path(tmpdir) / "slide")
        result = subprocess.run(
            ["pdftoppm", "-jpeg", "-r", str(dpi), tmp_pdf, prefix],
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            raise RuntimeError(f"pdftoppm failed:\n{result.stderr}")

        # Collect generated files (pdftoppm names them slide-01.jpg, slide-02.jpg, etc.)
        tmp_slides = sorted(Path(tmpdir).glob("slide-*.jpg"))
        if not tmp_slides:
            raise RuntimeError("No slide images generated by pdftoppm")

        # Copy to output directory with clean names
        slide_paths = []
        for i, src in enumerate(tmp_slides, 1):
            dst = output_dir / f"slide-{i:02d}.jpg"
            shutil.copy2(src, dst)
            slide_paths.append(str(dst))

    return slide_paths


def create_grid(slide_paths: list, output_path: str, cols: int = None, thumb_width: int = 480) -> str:
    """
    Create a grid overview image from individual slide images.

    Args:
        slide_paths: List of paths to slide JPG files
        output_path: Path for the output grid image
        cols: Number of columns (default: auto based on count)
        thumb_width: Width of each thumbnail in the grid (pixels)

    Returns:
        Path to the generated grid image.
    """
    try:
        from PIL import Image
    except ImportError:
        print("Warning: Pillow not installed. Skipping grid generation.")
        print("Install with: pip install Pillow --break-system-packages")
        return None

    if not slide_paths:
        raise ValueError("No slide images provided")

    # Auto-determine columns
    count = len(slide_paths)
    if cols is None:
        if count <= 4:
            cols = 2
        elif count <= 9:
            cols = 3
        else:
            cols = 4

    rows = math.ceil(count / cols)

    # Load first image to get aspect ratio
    with Image.open(slide_paths[0]) as sample:
        aspect = sample.width / sample.height

    thumb_height = int(thumb_width / aspect)
    padding = 10

    # Create grid canvas
    grid_w = cols * thumb_width + (cols + 1) * padding
    grid_h = rows * thumb_height + (rows + 1) * padding
    grid = Image.new("RGB", (grid_w, grid_h), (240, 240, 240))

    for idx, path in enumerate(slide_paths):
        row = idx // cols
        col = idx % cols
        x = padding + col * (thumb_width + padding)
        y = padding + row * (thumb_height + padding)

        with Image.open(path) as img:
            thumb = img.resize((thumb_width, thumb_height), Image.LANCZOS)
            grid.paste(thumb, (x, y))

    grid.save(output_path, "JPEG", quality=90)
    print(f"Grid: {output_path}")
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python thumbnail.py input.pptx [output_dir]")
        sys.exit(1)

    pptx_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else None

    slide_paths = pptx_to_slide_images(pptx_path, output_dir)
    for p in slide_paths:
        print(f"Slide: {p}")

    # Create grid in the same directory as slides
    grid_dir = Path(slide_paths[0]).parent
    grid_path = str(grid_dir / "grid.jpg")
    create_grid(slide_paths, grid_path)


if __name__ == "__main__":
    main()
